name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * 0'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push nezha-dashboard
        uses: docker/build-push-action@v3
        with:
          context: dashboard
          file: dashboard/Dockerfile
          platforms: linux/amd64, linux/arm64
          push: true
          tags: whoer/nezha-dashboard:latest
          
      -
        name: Build and push nezha-agent
        uses: docker/build-push-action@v3
        with:
          context: agent
          file: agent/Dockerfile
          platforms: linux/amd64, linux/arm64
          push: true
          tags: whoer/nezha-agent:latest
